version: '3.5'
services:
  postgres:
    container_name: webby_lab_db_postgres
    image: postgres:12.6
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webby_lab_db_postgres
    networks:
      - webbylab

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tac62/webbylab:0.1
    container_name: webby_lab_app
    env_file: .env
    restart: always
    environment:
      NODE_MODE: prod
    ports:
      - "8082:8082"
    networks:
      - webbylab

networks:
  webbylab:
    driver: "bridge"
